/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_durmiendo_sueno_temperature_NativeTemperature */

#ifndef _Included_org_durmiendo_sueno_temperature_NativeTemperature
#define _Included_org_durmiendo_sueno_temperature_NativeTemperature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_durmiendo_sueno_temperature_NativeTemperature
 * Method:    initNative
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_durmiendo_sueno_temperature_NativeTemperature_initNative
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_durmiendo_sueno_temperature_NativeTemperature
 * Method:    update
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_durmiendo_sueno_temperature_NativeTemperature_update
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
